// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkstjoocrpcykxirwqam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrc3Rqb29jcnBjeWt4aXJ3cWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDM5NjAsImV4cCI6MjA2MDcxOTk2MH0._npN0FJ9P4nyTahQB1mWUGAYBTVxEUnJQsu1wsHUFEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);